// Cleaned Excel Data
const rawExcelData = [
  {
    "year": 1990,
    "Age > born 1980": 10,
    "Net Money in the bank ( Worth )( spending )": 10,
    "Debt ( GBP K )": 0.0,
    "Net Position": 10.0,
    "Financial Baby Step": 1,
    "Rationale": "Experiment ( success driven )",
    "Type": "I",
    "Work Structure": "Probabilistic",
    "Market": "Financial",
    "Company Lead": "Stock market",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Stocks down",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "extracapital/financialgame",
    "Audience": "Family",
    "Marketing Type": "Push",
    "Lead Source": "Own Fantasy domestic",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 1.0,
    "Materials": "Newspaper",
    "COUNTRY": "TR",
    "location city ": "ankara",
    "delivery": "onsite",
    "mobility(km)": 0.0,
    "concurrency ": 1,
    "tax status": "",
    "role": "investor",
    "Duration month": 48,
    "type": "investing Wannabe",
    "Skills Added Symbols": "Turkish Read Write",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": 0,
    "Tax ( personal/Corporate )": 0,
    "increase rate to previous": 0,
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": 0.0,
    "state": "lost in time",
    "Asistants - Support": "family",
    "Description / GAP / Marketing / Learned ": "Zero marketing just gambling, production fear trawma at the age of 10 none-showup."
  },
  {
    "year": 1997,
    "Age > born 1980": "",
    "Net Money in the bank ( Worth )( spending )": "",
    "Debt ( GBP K )": "",
    "Net Position": 0.0,
    "Financial Baby Step": 1,
    "Rationale": "",
    "Type": "",
    "Work Structure": "Deterministic",
    "Market": "Education",
    "Company Lead": "School",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Math down",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Problem focused / English",
    "Audience": "Family",
    "Marketing Type": "Push",
    "Lead Source": "",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": "",
    "Materials": "",
    "COUNTRY": "",
    "location city ": "",
    "delivery": "onsite",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "First Principles",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 1998,
    "Age > born 1980": "",
    "Net Money in the bank ( Worth )( spending )": "",
    "Debt ( GBP K )": "",
    "Net Position": 0.0,
    "Financial Baby Step": 1,
    "Rationale": "",
    "Type": "",
    "Work Structure": "Probabilistic",
    "Market": "Education",
    "Company Lead": "AFS",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "USA up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "English  / multi culture workflows",
    "Audience": "Family ( host )",
    "Marketing Type": "Push",
    "Lead Source": "",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": "",
    "Materials": "",
    "COUNTRY": "",
    "location city ": "",
    "delivery": "onsite",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "English",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 1999,
    "Age > born 1980": 19,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 0.0,
    "Net Position": 0.0,
    "Financial Baby Step": 1,
    "Rationale": "Experiment ( failure driven )",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "Education",
    "Company Lead": "tutor",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Self Learning Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "problems with learning / gadgets, mobile customer development",
    "Audience": "a levels",
    "Marketing Type": "Push",
    "Lead Source": "Local referals",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 1.0,
    "Materials": "laptop",
    "COUNTRY": "TR",
    "location city ": "istanbul",
    "delivery": "onsite",
    "mobility(km)": 1.0,
    "concurrency ": 1,
    "tax status": "",
    "role": "teacher",
    "Duration month": 12,
    "type": "small business",
    "Skills Added Symbols": "Instruction",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": 2000,
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": 1.0,
    "state": "bougt laptop lost in girls",
    "Asistants - Support": "family",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 2000,
    "Age > born 1980": 20,
    "Net Money in the bank ( Worth )( spending )": 200,
    "Debt ( GBP K )": 0.0,
    "Net Position": 200.0,
    "Financial Baby Step": 1,
    "Rationale": "Bring Us to Tr       ( success driven)",
    "Type": "S",
    "Work Structure": "Deterministic - Probabilistic",
    "Market": "Real Estate",
    "Company Lead": "ilkon",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "Real Estate Down Franchise Up Brokerage Down",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "family extra capital / generalist,design patterns,pocs,microservices, teamwork,salesman,broker,franchisor,asistant manager",
    "Audience": "Turkish real estate entry",
    "Marketing Type": "Push",
    "Lead Source": "Local cold calling, Domestic cold calling",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 1.0,
    "Materials": "office spaces x3",
    "COUNTRY": "TR",
    "location city ": "istanbul - maslak",
    "delivery": "onsite",
    "mobility(km)": 0.0,
    "concurrency ": 1.1,
    "tax status": "",
    "role": "E(handson/tech),S(realestate/manage),B(franchise/scale/market),i(realestate/bookstore/investing), salesman - broker -franchiser - cto",
    "Duration month": 108,
    "type": "Big Business Wannabe",
    "Skills Added Symbols": "tester,POEAA,.net ,CSharp,SQL",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 2000,
    "pound per hour": -6.038647343,
    "production income": -1000000,
    "Corp/Customer Generated Revenue": 216000,
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": 7,
    "uk min wage": 1.333333333,
    "loose team count": 20.0,
    "state": "sunk cost fallacy",
    "Asistants - Support": "family > ilkonteam - serdar-murat-yalcin",
    "Description / GAP / Marketing / Learned ": "sales is not a \"muaaaa things\". cant do over mapping in the minds and preemptive strikes, unnecessary detail. Franchising plan did not turn out. I could not use the flipping oppurtunities."
  },
  {
    "year": 2010,
    "Age > born 1980": 30,
    "Net Money in the bank ( Worth )( spending )": 10,
    "Debt ( GBP K )": 30.0,
    "Net Position": -20.0,
    "Financial Baby Step": 1,
    "Rationale": "Experiment ( failure driven )",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "Dev",
    "Company Lead": "enterpro - turkcell / estore",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "wgggg",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "willing to start / introduction to contracting",
    "Audience": "Turkish enterprises",
    "Marketing Type": "Push",
    "Lead Source": "network referral",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 2.0,
    "Materials": "laptop",
    "COUNTRY": "TR",
    "location city ": "istanbul - besiktas - sisli",
    "delivery": "onsite",
    "mobility(km)": 100.0,
    "concurrency ": 3,
    "tax status": "",
    "role": "tester - business analysis - contract -  remote",
    "Duration month": 3,
    "type": "Family Business",
    "Skills Added Symbols": "Marketing,Sales,Oracle,Migrations,CRM, Salesforce.com",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 1500,
    "pound per hour": 4.528985507,
    "production income": 0,
    "Corp/Customer Generated Revenue": 4500,
    "Tax ( personal/Corporate )": 900,
    "increase rate to previous": "",
    "tr min wage": 5.555555556,
    "uk min wage": 1,
    "loose team count": 1.0,
    "state": "left",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "tutor only success with disabled learners. Icebreaker experiment contracting"
  },
  {
    "year": "SABBATICAL PIVOTS> ILKON OUT/2m out > Self Learn : Employment",
    "Age > born 1980": "",
    "Net Money in the bank ( Worth )( spending )": "",
    "Debt ( GBP K )": "",
    "Net Position": "",
    "Financial Baby Step": "",
    "Rationale": "",
    "Type": "",
    "Work Structure": "",
    "Market": "",
    "Company Lead": "",
    "Ocean Type": "",
    "Government": "",
    "BCI Direction     ( v SRE/ DEVOPS ^)": "",
    "Trending Keywords And Direction": "",
    "Passport Access": "",
    "Security Clearance": "",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "",
    "Audience": "",
    "Marketing Type": "",
    "Lead Source": "",
    "Passport/Visa": "",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": "",
    "Materials": "",
    "COUNTRY": "X > GAP : Family to Inland ( oblomov Land ^^^ )",
    "location city ": "",
    "delivery": "",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "",
    "Github Projects": "",
    "CV Linkedin Projects": "",
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 2011,
    "Age > born 1980": 31,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 0.0,
    "Net Position": 0.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential , Experiment",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "prominds",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Software Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "zero to jump / enterprise sales",
    "Audience": "Class room based learnign teens",
    "Marketing Type": "Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 3.0,
    "Materials": "their computer",
    "COUNTRY": "TR",
    "location city ": "istanbul - besiktas - sisli",
    "delivery": "onsite",
    "mobility(km)": 10.0,
    "concurrency ": 3,
    "tax status": "",
    "role": "teacher - tutor",
    "Duration month": 6,
    "type": "Employee",
    "Skills Added Symbols": "Excel, MVC, Tech Presentation",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 400,
    "pound per hour": 1.0,
    "production income": 0,
    "Corp/Customer Generated Revenue": 2400,
    "Tax ( personal/Corporate )": 480,
    "increase rate to previous": "",
    "tr min wage": 1.481481481,
    "uk min wage": 0.2666666667,
    "loose team count": 1.0,
    "state": "left",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "tutor only success with disabled learners. experience as a teacher. Marketed over friends. Health heart reboot. Importance of feedbacks > elon musk first principle thinking. Meet with Ece."
  },
  {
    "year": 2011,
    "Age > born 1980": 31,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 0.0,
    "Net Position": 0.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "bilgeadam",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Software Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "skills gap / take the leap, learn and teach",
    "Audience": "Class room based learnign teens",
    "Marketing Type": "Push",
    "Lead Source": "network referral",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 2.0,
    "Materials": "their computer / mine",
    "COUNTRY": "TR",
    "location city ": "istanbul - besiktas - sisli",
    "delivery": "onsite",
    "mobility(km)": 15.0,
    "concurrency ": 3,
    "tax status": "",
    "role": "teacher - tutor",
    "Duration month": 6,
    "type": "Employee",
    "Skills Added Symbols": "Java,Android,Eclipse",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 400,
    "pound per hour": 1.207729469,
    "production income": 0,
    "Corp/Customer Generated Revenue": 2400,
    "Tax ( personal/Corporate )": 480,
    "increase rate to previous": "",
    "tr min wage": 1.481481481,
    "uk min wage": 0.2666666667,
    "loose team count": 1.0,
    "state": "left",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "tutor only success with disabled learners. Friends marketing. Meet Firat who wants to do startup"
  },
  {
    "year": 2012,
    "Age > born 1980": 32,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 0.0,
    "Net Position": 0.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "wordego - ece",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Software Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "connect dots / learn aws",
    "Audience": "Enterprise Turkey management level",
    "Marketing Type": "Push",
    "Lead Source": "network referral",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 4.0,
    "Materials": "their computer/aws",
    "COUNTRY": "TR",
    "location city ": "istanbul - avcilar",
    "delivery": "onsite",
    "mobility(km)": 30.0,
    "concurrency ": 2,
    "tax status": "",
    "role": "senior developer - architect",
    "Duration month": 8,
    "type": "Employee",
    "Skills Added Symbols": "JQuery,Redis,AWS",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 500,
    "pound per hour": 1.509661836,
    "production income": 0,
    "Corp/Customer Generated Revenue": 4000,
    "Tax ( personal/Corporate )": 800,
    "increase rate to previous": 1.25,
    "tr min wage": 1.851851852,
    "uk min wage": 0.3333333333,
    "loose team count": 1.0,
    "state": "left",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "keywords in cv and not much supply in avcilar. Did not have enough money for a day gambling in cyprus."
  },
  {
    "year": 2013,
    "Age > born 1980": 33,
    "Net Money in the bank ( Worth )( spending )": 1,
    "Debt ( GBP K )": 0.0,
    "Net Position": 1.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "ages",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Software Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "team work / try new site 24x7",
    "Audience": "Enterprise Turkey management level",
    "Marketing Type": "Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 2.0,
    "Materials": "their computer/on prem",
    "COUNTRY": "TR",
    "location city ": "istanbul - maslak",
    "delivery": "onsite",
    "mobility(km)": 5.0,
    "concurrency ": 2,
    "tax status": "",
    "role": "manager",
    "Duration month": 6,
    "type": "Employee",
    "Skills Added Symbols": "Site24x7,Dependency Injection",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 600,
    "pound per hour": 1.811594203,
    "production income": 0,
    "Corp/Customer Generated Revenue": 3600,
    "Tax ( personal/Corporate )": 720,
    "increase rate to previous": 1.2,
    "tr min wage": 2.222222222,
    "uk min wage": 0.4,
    "loose team count": 1.0,
    "state": "sacked",
    "Asistants - Support": "Ece",
    "Description / GAP / Marketing / Learned ": "manager fail : aspie to connecto erbug cant manage to communicate with the stakeholders but good with the team. Management likes the delivery. Ioc did not know the load balancers and bigger enterprise actions"
  },
  {
    "year": 2014,
    "Age > born 1980": 34,
    "Net Money in the bank ( Worth )( spending )": 1,
    "Debt ( GBP K )": 0.0,
    "Net Position": 1.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "btctrader devops lead",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "teamwork(mohammad),cloud,trynew,snhu / azure,devops build,release pipelines",
    "Audience": "Enterprise Turkey management level",
    "Marketing Type": "Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 3.0,
    "Materials": "their computer/azure",
    "COUNTRY": "TR",
    "location city ": "istanbul - sisli",
    "delivery": "onsite",
    "mobility(km)": 15.0,
    "concurrency ": 2,
    "tax status": "",
    "role": "senior developer - architect",
    "Duration month": 9,
    "type": "Employee",
    "Skills Added Symbols": "DevOps,Azure,Rackspace",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 0.0,
    "pound month ( net/gross )": 800,
    "pound per hour": 2.415458937,
    "production income": 0,
    "Corp/Customer Generated Revenue": 7200,
    "Tax ( personal/Corporate )": 1440,
    "increase rate to previous": 1.333333333,
    "tr min wage": 2.962962963,
    "uk min wage": 0.5333333333,
    "loose team count": 1.0,
    "state": "left",
    "Asistants - Support": "Ece",
    "Description / GAP / Marketing / Learned ": "azure progress and focus on fixing bugs and CI/CD introduction. Entered the game of adding keywords and meet mohammed who was an expat. Use the Snhu as leverage"
  },
  {
    "year": 2015,
    "Age > born 1980": 35,
    "Net Money in the bank ( Worth )( spending )": 2,
    "Debt ( GBP K )": 0.0,
    "Net Position": 2.0,
    "Financial Baby Step": 3,
    "Rationale": "Marketing Leverage",
    "Type": "E>S",
    "Work Structure": "Deterministic / Probabilistic",
    "Market": "Dev",
    "Company Lead": "Accenture",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "afs,snhu,teamwork,design patterns / Estimations, Brand name,marketing with freelancer,costumes",
    "Audience": "Enterprise Turkey management level",
    "Marketing Type": "Pull / Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 5.0,
    "Materials": "their computers/X",
    "COUNTRY": "TR",
    "location city ": "Gebze",
    "delivery": "onsite",
    "mobility(km)": 100.0,
    "concurrency ": 1,
    "tax status": "",
    "role": "manager - poc - architect : support",
    "Duration month": 11,
    "type": "Employee",
    "Skills Added Symbols": "Management,SonarQube",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 1.0,
    "pound month ( net/gross )": 1000,
    "pound per hour": 3.019323671,
    "production income": 0,
    "Corp/Customer Generated Revenue": 11000,
    "Tax ( personal/Corporate )": 3300,
    "increase rate to previous": 1.25,
    "tr min wage": 3.703703704,
    "uk min wage": 0.6666666667,
    "loose team count": 2.0,
    "state": "left",
    "Asistants - Support": "Ece",
    "Description / GAP / Marketing / Learned ": "avoided management communication with success,enterprise name,Creative LinkedIn ages\nAFS american schools,Tolga director LinkedIn buildup is important hooks. Contractors make the most money(top guy accenture )"
  },
  {
    "year": 2016,
    "Age > born 1980": 36,
    "Net Money in the bank ( Worth )( spending )": 5,
    "Debt ( GBP K )": 0.0,
    "Net Position": 5.0,
    "Financial Baby Step": 3,
    "Rationale": "Marketing Leverage",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "Microsoft",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "teamwork,azure / Brand name , USA, Microsoft tools, Service Fabric Azure",
    "Audience": "Enterprises Global",
    "Marketing Type": "Pull / Push",
    "Lead Source": "network referral",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 6.0,
    "Materials": "their computer/azure",
    "COUNTRY": "TR",
    "location city ": "istanbul - levent - ankara - izmir - eskisehir",
    "delivery": "onsite",
    "mobility(km)": 800.0,
    "concurrency ": 1,
    "tax status": "",
    "role": "sales architect",
    "Duration month": 10,
    "type": "Employee",
    "Skills Added Symbols": "Azure, Networks, Cloud Computing",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 1.0,
    "pound month ( net/gross )": 3000,
    "pound per hour": 9.057971014,
    "production income": 0,
    "Corp/Customer Generated Revenue": 50000,
    "Tax ( personal/Corporate )": 17500,
    "increase rate to previous": 3,
    "tr min wage": 11.11111111,
    "uk min wage": 2,
    "loose team count": 2.0,
    "state": "sacked",
    "Asistants - Support": "Ece",
    "Description / GAP / Marketing / Learned ": "american money rocks. Sales fail cant do social with management, big name jump, currency jump makes sense. Linkedin is the base to grow, sales is not aspie thing too political."
  },
  {
    "year": 2016,
    "Age > born 1980": 36,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 10.0,
    "Net Position": -10.0,
    "Financial Baby Step": 2,
    "Rationale": "Antifragility",
    "Type": "E",
    "Work Structure": "Deterministic",
    "Market": "Dev",
    "Company Lead": "kariyermimari",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Gaming Down",
    "Passport Access": 111.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "tutoring sessions / Lean unity 3d",
    "Audience": "Class room based learning teens",
    "Marketing Type": "Pull / Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 4.0,
    "Materials": "mylaptop",
    "COUNTRY": "TR",
    "location city ": "istanbul - besiktas - sisli",
    "delivery": "onsite",
    "mobility(km)": 10.0,
    "concurrency ": 3,
    "tax status": "",
    "role": "teacher - tutor : unity",
    "Duration month": 6,
    "type": "Employee",
    "Skills Added Symbols": "Unity 3d, Unreal",
    "Github Projects": 0.0,
    "CV Linkedin Projects": 1.0,
    "pound month ( net/gross )": 400,
    "pound per hour": 1.207729469,
    "production income": 0,
    "Corp/Customer Generated Revenue": 2400,
    "Tax ( personal/Corporate )": 480,
    "increase rate to previous": "",
    "tr min wage": 1.481481481,
    "uk min wage": 0.2666666667,
    "loose team count": 2.0,
    "state": "left",
    "Asistants - Support": "Ece",
    "Description / GAP / Marketing / Learned ": "tutor only success with disabled learners.  turkey small market to do contracting. Go to a antifragile games training and fail on it ( success driven )"
  },
  {
    "year": "SABBATICAL PIVOTS > MS OUT>coup > Self Learn : PaperWork Gateways",
    "Age > born 1980": "",
    "Net Money in the bank ( Worth )( spending )": "",
    "Debt ( GBP K )": "",
    "Net Position": "",
    "Financial Baby Step": "",
    "Rationale": "",
    "Type": "",
    "Work Structure": "",
    "Market": "",
    "Company Lead": "",
    "Ocean Type": "",
    "Government": "",
    "BCI Direction     ( v SRE/ DEVOPS ^)": "",
    "Trending Keywords And Direction": "",
    "Passport Access": "",
    "Security Clearance": "",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "",
    "Audience": "",
    "Marketing Type": "",
    "Lead Source": "",
    "Passport/Visa": "",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": "",
    "Materials": "",
    "COUNTRY": "E to S > Gap : 7 month  - VISA",
    "location city ": "",
    "delivery": "",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "",
    "Github Projects": "",
    "CV Linkedin Projects": "",
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 2017,
    "Age > born 1980": 37,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 20.0,
    "Net Position": -20.0,
    "Financial Baby Step": 1,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "Dev to Ops",
    "Company Lead": "holovis contract",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "Gaming Down",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Unity3d, Azure,English / get the initial UK Contract",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 7.0,
    "Materials": "my laptop / my 40 item bag",
    "COUNTRY": "UK",
    "location city ": "uk -rugby",
    "delivery": "onsite",
    "mobility(km)": 2000.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "handson architect (developer ): support : unity",
    "Duration month": 1,
    "type": "Small Business",
    "Skills Added Symbols": "Immigration",
    "Github Projects": 2.0,
    "CV Linkedin Projects": 2.0,
    "pound month ( net/gross )": 5000,
    "pound per hour": 15.09661836,
    "production income": 0,
    "Corp/Customer Generated Revenue": 5000,
    "Tax ( personal/Corporate )": 8300,
    "increase rate to previous": 1.666666667,
    "tr min wage": 18.51851852,
    "uk min wage": 3.333333333,
    "loose team count": 3.0,
    "state": "renew",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "first contract in Uk.push marketing Stratford London, architect roles don't work emre akarsu. Conation quickstart focus. Miniu extend for a week"
  },
  {
    "year": 2017,
    "Age > born 1980": 37,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 10.0,
    "Net Position": -10.0,
    "Financial Baby Step": 1,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "ticket arena contract",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Azure , Service Fabric / Microservices, DevOps Contracting",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 8.0,
    "Materials": "my laptop / my 40 item bag",
    "COUNTRY": "UK",
    "location city ": "uk - leeds",
    "delivery": "onsite",
    "mobility(km)": 300.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 2,
    "type": "Small Business",
    "Skills Added Symbols": "AZDO",
    "Github Projects": 3.0,
    "CV Linkedin Projects": 3.0,
    "pound month ( net/gross )": 6000,
    "pound per hour": 18.11594203,
    "production income": 0,
    "Corp/Customer Generated Revenue": 12000,
    "Tax ( personal/Corporate )": 8300,
    "increase rate to previous": 1.2,
    "tr min wage": 22.22222222,
    "uk min wage": 4,
    "loose team count": 3.0,
    "state": "sacked > with team",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "contracting unknown time and mobile. 40 items focused on adapting as much as i can. Sacked all the team"
  },
  {
    "year": 2017,
    "Age > born 1980": 37,
    "Net Money in the bank ( Worth )( spending )": 0,
    "Debt ( GBP K )": 10.0,
    "Net Position": -10.0,
    "Financial Baby Step": 1,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "scottish enterprise contract",
    "Ocean Type": "Blue",
    "Government": 1.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "BPSS",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "move there, Azure , teamwork, devops / Pipelines by Microsoft, negotiate contracts, marketing in contracts, security clerance",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 8.0,
    "Materials": "my laptop / my 40 item bag",
    "COUNTRY": "UK",
    "location city ": "uk - scotland - glasgow",
    "delivery": "onsite",
    "mobility(km)": 250.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "handson architect : support",
    "Duration month": 8,
    "type": "Small Business",
    "Skills Added Symbols": "App Services,Microservices, Selenium",
    "Github Projects": 4.0,
    "CV Linkedin Projects": 4.0,
    "pound month ( net/gross )": 8000,
    "pound per hour": 24.15458937,
    "production income": 0,
    "Corp/Customer Generated Revenue": 64000,
    "Tax ( personal/Corporate )": 8300,
    "increase rate to previous": 1.333333333,
    "tr min wage": 29.62962963,
    "uk min wage": 5.333333333,
    "loose team count": 3.0,
    "state": "renew",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "ask for more and take chances"
  },
  {
    "year": 2018,
    "Age > born 1980": 38,
    "Net Money in the bank ( Worth )( spending )": 5,
    "Debt ( GBP K )": 0.0,
    "Net Position": 5.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "craneware contract",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "move there, Azure , devops / Chatops automation",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "domestic portal application local jobs",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 8.0,
    "Materials": "my laptop / my 40 item bag",
    "COUNTRY": "UK",
    "location city ": "uk - scotland - edinburgh",
    "delivery": "onsite",
    "mobility(km)": 100.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "architect : engineer",
    "Duration month": 3,
    "type": "Small Business",
    "Skills Added Symbols": "Chatops",
    "Github Projects": 5.0,
    "CV Linkedin Projects": 5.0,
    "pound month ( net/gross )": 9000,
    "pound per hour": 27.17391304,
    "production income": 0,
    "Corp/Customer Generated Revenue": 27000,
    "Tax ( personal/Corporate )": 7500,
    "increase rate to previous": 1.125,
    "tr min wage": 33.33333333,
    "uk min wage": 6,
    "loose team count": 4.0,
    "state": "completed",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "real contractor rates, do your own thing continue. Google did not pay as well as a contract. Management asks something different. Parkistan Hassan"
  },
  {
    "year": 2018,
    "Age > born 1980": 38,
    "Net Money in the bank ( Worth )( spending )": 10,
    "Debt ( GBP K )": 0.0,
    "Net Position": 10.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "mmt contract",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "move there, architecture, teamwork, Azure , devops / ASE Contracts",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "my laptop / my 40 item bag",
    "COUNTRY": "UK",
    "location city ": "uk - uppingham",
    "delivery": "onsite",
    "mobility(km)": 300.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "handson architect : support",
    "Duration month": 3,
    "type": "Small Business",
    "Skills Added Symbols": "Docker,ASE",
    "Github Projects": 6.0,
    "CV Linkedin Projects": 6.0,
    "pound month ( net/gross )": 10000,
    "pound per hour": 30.19323671,
    "production income": 0,
    "Corp/Customer Generated Revenue": 30000,
    "Tax ( personal/Corporate )": 7500,
    "increase rate to previous": 1.111111111,
    "tr min wage": 37.03703704,
    "uk min wage": 6.666666667,
    "loose team count": 4.0,
    "state": "left",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "marketing on the linkedin repeat network,I can live in a market town, Eric meetups where he also leverages himself out of the market town"
  },
  {
    "year": 2018,
    "Age > born 1980": 38,
    "Net Money in the bank ( Worth )( spending )": 20,
    "Debt ( GBP K )": 0.0,
    "Net Position": 20.0,
    "Financial Baby Step": 2,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "rbr contract",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "move there, Azure , devops / Kubernetes, Gaming  clubs",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 6.0,
    "Materials": "my laptop / my 40 item bag",
    "COUNTRY": "UK",
    "location city ": "uk - nottingham",
    "delivery": "onsite",
    "mobility(km)": 200.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 2,
    "type": "Small Business",
    "Skills Added Symbols": "Kubernetes,Conjure,ELK",
    "Github Projects": 7.0,
    "CV Linkedin Projects": 7.0,
    "pound month ( net/gross )": 12000,
    "pound per hour": 36.23188406,
    "production income": 0,
    "Corp/Customer Generated Revenue": 24000,
    "Tax ( personal/Corporate )": 7500,
    "increase rate to previous": 1.2,
    "tr min wage": 44.44444444,
    "uk min wage": 8,
    "loose team count": 4.0,
    "state": "kickedout > kubernetes",
    "Asistants - Support": "myself",
    "Description / GAP / Marketing / Learned ": "political staff happens in companies no need to overplay in your head. you are an aspie not as fast as neurotypicals in new things learning and implementing"
  },
  {
    "year": 2018,
    "Age > born 1980": 38,
    "Net Money in the bank ( Worth )( spending )": 30,
    "Debt ( GBP K )": 0.0,
    "Net Position": 30.0,
    "Financial Baby Step": 2,
    "Rationale": "Marketing Leverage",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "smartspace",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "move there, Azure , devops, Service Fabric / Gaming  clubs, London contract, Octopus",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 7.0,
    "Materials": "my laptop / my 2 bag",
    "COUNTRY": "UK",
    "location city ": "uk -luton",
    "delivery": "onsite",
    "mobility(km)": 150.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 5,
    "type": "Small Business",
    "Skills Added Symbols": "Service Fabric",
    "Github Projects": 8.0,
    "CV Linkedin Projects": 8.0,
    "pound month ( net/gross )": 15840,
    "pound per hour": 47.82608696,
    "production income": 0,
    "Corp/Customer Generated Revenue": 79200,
    "Tax ( personal/Corporate )": 7500,
    "increase rate to previous": 1.32,
    "tr min wage": 58.66666667,
    "uk min wage": 10.56,
    "loose team count": 5.0,
    "state": "completed",
    "Asistants - Support": "Caglar",
    "Description / GAP / Marketing / Learned ": "Got the same money in worst place but had london in its name and banking. Worked on haigh administration issue"
  },
  {
    "year": 2019,
    "Age > born 1980": 39,
    "Net Money in the bank ( Worth )( spending )": 40,
    "Debt ( GBP K )": 0.0,
    "Net Position": 40.0,
    "Financial Baby Step": 3,
    "Rationale": "Marketing Leverage",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "concentra  contract",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "background check",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "azure, microsoft / london contract, pthyon",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 6.0,
    "Materials": "my laptop / home studio",
    "COUNTRY": "UK",
    "location city ": "UK- london",
    "delivery": "onsite",
    "mobility(km)": 150.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 7,
    "type": "Small Business",
    "Skills Added Symbols": "Python,Terraform",
    "Github Projects": 9.0,
    "CV Linkedin Projects": 9.0,
    "pound month ( net/gross )": 19720,
    "pound per hour": 59.5410628,
    "production income": 0,
    "Corp/Customer Generated Revenue": 138040,
    "Tax ( personal/Corporate )": 10000,
    "increase rate to previous": 1.244949495,
    "tr min wage": 73.03703704,
    "uk min wage": 13.14666667,
    "loose team count": 5.0,
    "state": "sacked",
    "Asistants - Support": "Caglar",
    "Description / GAP / Marketing / Learned ": "London name and banking helper to settle. 700 pound contracts, market limits ?"
  },
  {
    "year": 2019,
    "Age > born 1980": 39,
    "Net Money in the bank ( Worth )( spending )": 50,
    "Debt ( GBP K )": 0.0,
    "Net Position": 50.0,
    "Financial Baby Step": 3,
    "Rationale": "Marketing Leverage",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "ardent blue contract",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "python, gaming experience, estimations / usa contract, remote contract, wire transfer, south america contract",
    "Audience": "Usa enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 8.0,
    "Materials": "home studio",
    "COUNTRY": "USA",
    "location city ": "New York",
    "delivery": "remote",
    "mobility(km)": 3000.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer : unity",
    "Duration month": 2,
    "type": "Small Business",
    "Skills Added Symbols": "AWS Step functions, Lambda",
    "Github Projects": 10.0,
    "CV Linkedin Projects": 10.0,
    "pound month ( net/gross )": 22000,
    "pound per hour": 137.5,
    "production income": 0,
    "Corp/Customer Generated Revenue": 44000,
    "Tax ( personal/Corporate )": 10000,
    "increase rate to previous": 1.115618661,
    "tr min wage": 81.48148148,
    "uk min wage": 14.66666667,
    "loose team count": 5.0,
    "state": "completed",
    "Asistants - Support": "Caglar - Ece",
    "Description / GAP / Marketing / Learned ": "Us contract multiple continents and use of serverless hardcore with step functions."
  },
  {
    "year": 2020,
    "Age > born 1980": 39,
    "Net Money in the bank ( Worth )( spending )": "SABBATICAL PIVOTS > COVID : > Self Learn :Content",
    "Debt ( GBP K )": "",
    "Net Position": "",
    "Financial Baby Step": "",
    "Rationale": "",
    "Type": "",
    "Work Structure": "",
    "Market": "",
    "Company Lead": "",
    "Ocean Type": "",
    "Government": "",
    "BCI Direction     ( v SRE/ DEVOPS ^)": "down",
    "Trending Keywords And Direction": "",
    "Passport Access": "",
    "Security Clearance": "",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "",
    "Audience": "",
    "Marketing Type": "",
    "Lead Source": "",
    "Passport/Visa": "",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": "",
    "Materials": "",
    "COUNTRY": "",
    "location city ": "Gap : Corona >",
    "delivery": "",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "",
    "Github Projects": "",
    "CV Linkedin Projects": "",
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 2020,
    "Age > born 1980": 40,
    "Net Money in the bank ( Worth )( spending )": 85,
    "Debt ( GBP K )": 70.0,
    "Net Position": 15.0,
    "Financial Baby Step": "2023-04-03T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Canada Life",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "azure,microservices,devops,octopus / work from home, video production studio",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 7.0,
    "Materials": "home studio",
    "COUNTRY": "UK",
    "location city ": "London North",
    "delivery": "remote",
    "mobility(km)": 100.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 3,
    "type": "Small Business",
    "Skills Added Symbols": "APIM",
    "Github Projects": 15.0,
    "CV Linkedin Projects": 10.0,
    "pound month ( net/gross )": 11500,
    "pound per hour": 71.875,
    "production income": 0,
    "Corp/Customer Generated Revenue": 34500,
    "Tax ( personal/Corporate )": 10000,
    "increase rate to previous": "#DIV/0!",
    "tr min wage": 42.59259259,
    "uk min wage": 7.666666667,
    "loose team count": 7.0,
    "state": "renew",
    "Asistants - Support": "Caglar - Ece",
    "Description / GAP / Marketing / Learned ": "Parkistan Ali abdaal see in garage stop the car."
  },
  {
    "year": 2021,
    "Age > born 1980": 41,
    "Net Money in the bank ( Worth )( spending )": 85,
    "Debt ( GBP K )": 80.0,
    "Net Position": 5.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Canada Life,Theta",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "azure / logic apps infra as code",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 7.0,
    "Materials": "home studio",
    "COUNTRY": "UK",
    "location city ": "London North",
    "delivery": "remote",
    "mobility(km)": 100.0,
    "concurrency ": 2,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 4,
    "type": "Small Business",
    "Skills Added Symbols": "Logic Apps",
    "Github Projects": 15.0,
    "CV Linkedin Projects": 15.0,
    "pound month ( net/gross )": 24840,
    "pound per hour": 155.25,
    "production income": 0,
    "Corp/Customer Generated Revenue": 99360,
    "Tax ( personal/Corporate )": 10000,
    "increase rate to previous": 2.16,
    "tr min wage": 92,
    "uk min wage": 16.56,
    "loose team count": 7.0,
    "state": "renew",
    "Asistants - Support": "Caglar - Ece-Mehmet",
    "Description / GAP / Marketing / Learned ": "Double action fear and overcome"
  },
  {
    "year": 2021,
    "Age > born 1980": 41,
    "Net Money in the bank ( Worth )( spending )": 85,
    "Debt ( GBP K )": 100.0,
    "Net Position": -15.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Canada Life",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "azure / apim automation",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 7.0,
    "Materials": "home studio",
    "COUNTRY": "UK",
    "location city ": "London North",
    "delivery": "remote",
    "mobility(km)": 100.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 1,
    "type": "Small Business",
    "Skills Added Symbols": "Octopus",
    "Github Projects": 15.0,
    "CV Linkedin Projects": 20.0,
    "pound month ( net/gross )": 11500,
    "pound per hour": 71.875,
    "production income": 0,
    "Corp/Customer Generated Revenue": 11500,
    "Tax ( personal/Corporate )": 10000,
    "increase rate to previous": 0.462962963,
    "tr min wage": 42.59259259,
    "uk min wage": 7.666666667,
    "loose team count": 7.0,
    "state": "sacked > with team ( later on )",
    "Asistants - Support": "Anjum - Caglar - Ece - X(cocreators)",
    "Description / GAP / Marketing / Learned ": "Relax and focus on the team for them to REUSE and create a usable video for the consumer."
  },
  {
    "year": 2021,
    "Age > born 1980": 41,
    "Net Money in the bank ( Worth )( spending )": 120,
    "Debt ( GBP K )": 80.0,
    "Net Position": 40.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "CW",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "infrastructure as code, azure, costumes / post production tools",
    "Audience": "Uk enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "Wework / gadgets",
    "COUNTRY": "UK-USA",
    "location city ": "London Central",
    "delivery": "remote",
    "mobility(km)": 150.0,
    "concurrency ": "2021-03-02T00:00:00",
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 6,
    "type": "Small Business",
    "Skills Added Symbols": "IAC",
    "Github Projects": 15.0,
    "CV Linkedin Projects": 25.0,
    "pound month ( net/gross )": 11500,
    "pound per hour": 71.875,
    "production income": 0,
    "Corp/Customer Generated Revenue": 69000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 1,
    "tr min wage": 42.59259259,
    "uk min wage": 7.666666667,
    "loose team count": 5.0,
    "state": "extended",
    "Asistants - Support": "Anjum - Caglar - Ece - X(cocreators)",
    "Description / GAP / Marketing / Learned ": "connect the dots move to a better location for recording. Everything is not money family visits"
  },
  {
    "year": 2021,
    "Age > born 1980": 41,
    "Net Money in the bank ( Worth )( spending )": 120,
    "Debt ( GBP K )": 80.0,
    "Net Position": 40.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "QCK",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Azure / Infra as code",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "Wework / gadgets",
    "COUNTRY": "IRELAND_GERMANY",
    "location city ": "Austria",
    "delivery": "remote",
    "mobility(km)": 1000.0,
    "concurrency ": "2021-03-02T00:00:00",
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 6,
    "type": "Small Business",
    "Skills Added Symbols": "NVidia",
    "Github Projects": 20.0,
    "CV Linkedin Projects": 30.0,
    "pound month ( net/gross )": 11500,
    "pound per hour": 71.875,
    "production income": 0,
    "Corp/Customer Generated Revenue": 69000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 1,
    "tr min wage": 42.59259259,
    "uk min wage": 7.666666667,
    "loose team count": 5.0,
    "state": "extended",
    "Asistants - Support": "Anjum - Caglar - Ece - X(cocreators)",
    "Description / GAP / Marketing / Learned ": "Move to AI and the preprod work should be done in the problems that i solve can be presented with energy"
  },
  {
    "year": 2021,
    "Age > born 1980": 41,
    "Net Money in the bank ( Worth )( spending )": 120,
    "Debt ( GBP K )": 70.0,
    "Net Position": 50.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Theta",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "apim automation / multi roles possible/notpossible",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 10.0,
    "Materials": "home studio",
    "COUNTRY": "UK",
    "location city ": "London Central",
    "delivery": "remote",
    "mobility(km)": 150.0,
    "concurrency ": "2021-03-02T00:00:00",
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 1,
    "type": "Small Business",
    "Skills Added Symbols": "Connectors",
    "Github Projects": 25.0,
    "CV Linkedin Projects": 35.0,
    "pound month ( net/gross )": 5000,
    "pound per hour": 31.25,
    "production income": 0,
    "Corp/Customer Generated Revenue": 5000,
    "Tax ( personal/Corporate )": 1000,
    "increase rate to previous": 0.4347826087,
    "tr min wage": 18.51851852,
    "uk min wage": 3.333333333,
    "loose team count": 6.0,
    "state": "ended -burnout",
    "Asistants - Support": "Anjum - Caglar - Ece - X(cocreators)",
    "Description / GAP / Marketing / Learned ": "Daisy chain and have backup for the ILR system"
  },
  {
    "year": 2021,
    "Age > born 1980": 41,
    "Net Money in the bank ( Worth )( spending )": 120,
    "Debt ( GBP K )": 70.0,
    "Net Position": 50.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "I",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Etoro",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "Finance Down",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "extra cash / financal rules",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "Own Fantasy global",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 2.0,
    "Materials": "site and aggregators",
    "COUNTRY": "UK",
    "location city ": "Cyprus",
    "delivery": "remote",
    "mobility(km)": 2500.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "investor",
    "Duration month": 1,
    "type": "Investor",
    "Skills Added Symbols": "Finance,Forex,Markets",
    "Github Projects": 30.0,
    "CV Linkedin Projects": 40.0,
    "pound month ( net/gross )": 100,
    "pound per hour": 0.625,
    "production income": 0,
    "Corp/Customer Generated Revenue": 100,
    "Tax ( personal/Corporate )": 0,
    "increase rate to previous": 0.02,
    "tr min wage": 0.3703703704,
    "uk min wage": 0.06666666667,
    "loose team count": 6.0,
    "state": "> exit due to ECAA application",
    "Asistants - Support": "Anjum - Caglar - Ece - X(cocreators)",
    "Description / GAP / Marketing / Learned ": "Forex back up > 15k >10 percent loss GBP to dollar and 10k to Pinar for her to buy a house"
  },
  {
    "year": 2022,
    "Age > born 1980": 42,
    "Net Money in the bank ( Worth )( spending )": 100,
    "Debt ( GBP K )": 60.0,
    "Net Position": 40.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "CW",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "infrastructure as code, azure, costumes / post production tools",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "Wework / gadgets",
    "COUNTRY": "UK-USA",
    "location city ": "London Central",
    "delivery": "remote",
    "mobility(km)": 150.0,
    "concurrency ": "2021-03-02T00:00:00",
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 9,
    "type": "Small Business",
    "Skills Added Symbols": "Immutable Infra",
    "Github Projects": 35.0,
    "CV Linkedin Projects": 45.0,
    "pound month ( net/gross )": 11500,
    "pound per hour": 71.875,
    "production income": 0,
    "Corp/Customer Generated Revenue": 103500,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 115,
    "tr min wage": 42.59259259,
    "uk min wage": 7.666666667,
    "loose team count": 5.0,
    "state": "natural end > accenture like",
    "Asistants - Support": "Anjum - Caglar - Ece",
    "Description / GAP / Marketing / Learned ": "Mentoring baris, smaller production team"
  },
  {
    "year": 2022,
    "Age > born 1980": 42,
    "Net Money in the bank ( Worth )( spending )": 80,
    "Debt ( GBP K )": 40.0,
    "Net Position": 40.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "QCK",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Up",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Azure / Infra as code present and the udemy course",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "Wework / gadgets",
    "COUNTRY": "IRELAND_GERMANY",
    "location city ": "Austria",
    "delivery": "remote",
    "mobility(km)": 1000.0,
    "concurrency ": "2021-03-02T00:00:00",
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 6,
    "type": "Small Business",
    "Skills Added Symbols": "Pip",
    "Github Projects": 40.0,
    "CV Linkedin Projects": 50.0,
    "pound month ( net/gross )": 11500,
    "pound per hour": 71.875,
    "production income": 0,
    "Corp/Customer Generated Revenue": 69000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 1,
    "tr min wage": 42.59259259,
    "uk min wage": 7.666666667,
    "loose team count": 5.0,
    "state": "natural end",
    "Asistants - Support": "Anjum - Caglar - Ece",
    "Description / GAP / Marketing / Learned ": "Decided on Ultimate Guide on DevOps Engineering for Contractors"
  },
  {
    "year": 2022,
    "Age > born 1980": 42,
    "Net Money in the bank ( Worth )( spending )": 60,
    "Debt ( GBP K )": 30.0,
    "Net Position": 30.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "EMERSON",
    "Ocean Type": "Red",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Stable",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Oxford relationship,Kubernetes/ USA Company",
    "Audience": "Usa enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "USA C2C Remote",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 6.0,
    "Materials": "Wework / gadgets",
    "COUNTRY": "USA - SPAIN - FRANCE - SWITZERLAND -UK",
    "location city ": "Paris",
    "delivery": "remote",
    "mobility(km)": 750.0,
    "concurrency ": 2,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 2,
    "type": "Small Business",
    "Skills Added Symbols": "Kubernetes, Community Management",
    "Github Projects": 45.0,
    "CV Linkedin Projects": 55.0,
    "pound month ( net/gross )": 8000,
    "pound per hour": 50.0,
    "production income": 0,
    "Corp/Customer Generated Revenue": 16000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 0.6956521739,
    "tr min wage": 29.62962963,
    "uk min wage": 5.333333333,
    "loose team count": 5.0,
    "state": "kickedout > kubernetes",
    "Asistants - Support": "Anjum - Caglar - Ece",
    "Description / GAP / Marketing / Learned ": "Swiss company did it, followed up all the incfile work, usa first blood"
  },
  {
    "year": 2022,
    "Age > born 1980": 42,
    "Net Money in the bank ( Worth )( spending )": 20,
    "Debt ( GBP K )": 50.0,
    "Net Position": -30.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Ypsomed",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Stable",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Oxford relationship,Migration keyword, Azure/ Switzerland Role , Immigration course",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "Wework / gadgets",
    "COUNTRY": "SWITZERLAND",
    "location city ": "Solothurn Switzerland",
    "delivery": "hybrid",
    "mobility(km)": 1500.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 6,
    "type": "Small Business",
    "Skills Added Symbols": "Git, Migration planning, Wordpress",
    "Github Projects": 50.0,
    "CV Linkedin Projects": 60.0,
    "pound month ( net/gross )": 10000,
    "pound per hour": 62.5,
    "production income": 0,
    "Corp/Customer Generated Revenue": 60000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 1.25,
    "tr min wage": 37.03703704,
    "uk min wage": 6.666666667,
    "loose team count": 5.0,
    "state": "new",
    "Asistants - Support": "Anjum - Caglar - Ece - Oyku - Kajla",
    "Description / GAP / Marketing / Learned ": "Same agency tripple contracts > IR35 and visa mitigation"
  },
  {
    "year": 2023,
    "Age > born 1980": 43,
    "Net Money in the bank ( Worth )( spending )": 15,
    "Debt ( GBP K )": 45.0,
    "Net Position": -30.0,
    "Financial Baby Step": "2023-04-02T00:00:00",
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Ypsomed",
    "Ocean Type": "Blue",
    "Government": 0.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Stable",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Extension TFS migration, consistency",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "global portal application",
    "Passport/Visa": "Turkish Passport + ECAA",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 8.0,
    "Materials": "Napier",
    "COUNTRY": "SWITZERLAND",
    "location city ": "Solothurn Switzerland",
    "delivery": "remote",
    "mobility(km)": 1500.0,
    "concurrency ": 1,
    "tax status": "outside ir35",
    "role": "devops engineer",
    "Duration month": 3,
    "type": "Small Business",
    "Skills Added Symbols": "TFS,Miro",
    "Github Projects": 55.0,
    "CV Linkedin Projects": 65.0,
    "pound month ( net/gross )": 10000,
    "pound per hour": 62.5,
    "production income": 0,
    "Corp/Customer Generated Revenue": 30000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 1,
    "tr min wage": 37.03703704,
    "uk min wage": 6.666666667,
    "loose team count": 5.0,
    "state": "renew",
    "Asistants - Support": "Affiliates - Ece",
    "Description / GAP / Marketing / Learned ": "ILR limbo period"
  },
  {
    "year": 2023,
    "Age > born 1980": 43,
    "Net Money in the bank ( Worth )( spending )": 6,
    "Debt ( GBP K )": 36.0,
    "Net Position": -30.0,
    "Financial Baby Step": 3,
    "Rationale": "Existential",
    "Type": "S",
    "Work Structure": "Probabilistic",
    "Market": "DevOps",
    "Company Lead": "Ypsomed (3) , CPrime (5)",
    "Ocean Type": "Blue",
    "Government": 1.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "DevOps Stable",
    "Passport Access": 112.0,
    "Security Clearance": "-",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "Extension TFS migration, Omad",
    "Audience": "Global enterprises",
    "Marketing Type": "Pull / Push",
    "Lead Source": "Linkedin and referals",
    "Passport/Visa": "Turkish Passport + ILR",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 9.0,
    "Materials": "Macbook pro/xps backpack",
    "COUNTRY": "REMOTE SWISS / OMAN ONSITE",
    "location city ": "Muscat / Room",
    "delivery": "onsite",
    "mobility(km)": 10000.0,
    "concurrency ": 2,
    "tax status": "outside ir35",
    "role": "devops lead",
    "Duration month": 3,
    "type": "Employee, Business",
    "Skills Added Symbols": "Release Train Engineering, GPT, Workrlows, Onpremise gateways",
    "Github Projects": 60.0,
    "CV Linkedin Projects": 72.0,
    "pound month ( net/gross )": 30000,
    "pound per hour": 187.5,
    "production income": 0,
    "Corp/Customer Generated Revenue": 90000,
    "Tax ( personal/Corporate )": 3000,
    "increase rate to previous": 3,
    "tr min wage": 111.1111111,
    "uk min wage": 20,
    "loose team count": 5.0,
    "state": "natural end, terminated",
    "Asistants - Support": "Upwork sow based low perform Anjum,Caglar,Rachel > Ece offline depression",
    "Description / GAP / Marketing / Learned ": "Out of the limbo but landed at the start while Funding circle offered at 30 percent. Oman with expenses paid system over the Goldman sachs"
  },
  {
    "year": "SABBATICAL PIVOTS > FAMILY EMERGENCY > Self Learn : Niche / Funnel",
    "Age > born 1980": "",
    "Net Money in the bank ( Worth )( spending )": "",
    "Debt ( GBP K )": "",
    "Net Position": "",
    "Financial Baby Step": "",
    "Rationale": "",
    "Type": "",
    "Work Structure": "",
    "Market": "",
    "Company Lead": "",
    "Ocean Type": "",
    "Government": "",
    "BCI Direction     ( v SRE/ DEVOPS ^)": "DOWN",
    "Trending Keywords And Direction": "",
    "Passport Access": "",
    "Security Clearance": "",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "",
    "Audience": "",
    "Marketing Type": "",
    "Lead Source": "",
    "Passport/Visa": "",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": "",
    "Materials": "",
    "COUNTRY": "S to B > move to production(B) > finance (I)",
    "location city ": "",
    "delivery": "",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "",
    "Github Projects": "",
    "CV Linkedin Projects": "",
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  },
  {
    "year": 2024,
    "Age > born 1980": 44,
    "Net Money in the bank ( Worth )( spending )": 10,
    "Debt ( GBP K )": 60.0,
    "Net Position": -50.0,
    "Financial Baby Step": "2024-02-01T00:00:00",
    "Rationale": "Existential",
    "Type": "E/S",
    "Work Structure": "Deterministic - Probalistic",
    "Market": "DevOps",
    "Company Lead": "IBM / SSE",
    "Ocean Type": "Red",
    "Government": 1.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP/DOWN",
    "Trending Keywords And Direction": "SRE",
    "Passport Access": 185.0,
    "Security Clearance": "uk_bpss > nsv_europe,nato",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "numbers is lead generation 80 per cent fail. High tech geek sells",
    "Audience": "Domestic Enterprise -Security Clearance",
    "Marketing Type": "Pull / Push",
    "Lead Source": "Linkedin",
    "Passport/Visa": "Turkish  + Nato Security Clerance",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 10.0,
    "Materials": "Workstation",
    "COUNTRY": "UK READING",
    "location city ": "READING UK",
    "delivery": "hybrid",
    "mobility(km)": 150.0,
    "concurrency ": 1,
    "tax status": "inside ir35",
    "role": "SRE",
    "Duration month": 24,
    "type": "Employee, Business",
    "Skills Added Symbols": "Openshift / Kubernetes / Screen Writing",
    "Github Projects": 120.0,
    "CV Linkedin Projects": 72.0,
    "pound month ( net/gross )": 6000,
    "pound per hour": 37.5,
    "production income": 0,
    "Corp/Customer Generated Revenue": 104000,
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "Support All Family > Ece mental support",
    "Description / GAP / Marketing / Learned ": "Complex cluster management > universal credit > second brain / 1000 expenses monthly"
  },
  {
    "year": 2025,
    "Age > born 1980": 45,
    "Net Money in the bank ( Worth )( spending )": 10,
    "Debt ( GBP K )": 60.0,
    "Net Position": -50.0,
    "Financial Baby Step": "2024-02-01T00:00:00",
    "Rationale": "Existential",
    "Type": "E/S",
    "Work Structure": "Deterministic - Probalistic",
    "Market": "SRE",
    "Company Lead": "IBM / SSE",
    "Ocean Type": "Red",
    "Government": 1.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP/DOWN",
    "Trending Keywords And Direction": "SRE",
    "Passport Access": 185.0,
    "Security Clearance": "uk_bpss > nsv_europe,nato",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "numbers is lead generation 80 per cent fail. High tech geek sells",
    "Audience": "Domestic Enterprise -Security Clearance",
    "Marketing Type": "Pull / Push",
    "Lead Source": "Linkedin",
    "Passport/Visa": "British  + Nato Security Clerance",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 10.0,
    "Materials": "Workstation",
    "COUNTRY": "UK READING",
    "location city ": "READING UK",
    "delivery": "hybrid",
    "mobility(km)": 150.0,
    "concurrency ": 1,
    "tax status": "inside ir35",
    "role": "SRE",
    "Duration month": 24,
    "type": "Employee, Business",
    "Skills Added Symbols": "Openshift / Kubernetes / Screen Writing",
    "Github Projects": 120.0,
    "CV Linkedin Projects": 72.0,
    "pound month ( net/gross )": 6000,
    "pound per hour": 37.5,
    "production income": 0,
    "Corp/Customer Generated Revenue": 104000,
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "Support All Family > Ece mental support",
    "Description / GAP / Marketing / Learned ": "Complex cluster management > universal credit > llm  / 1500 expenses monthly"
  },
  {
    "year": 2026,
    "Age > born 1980": 46,
    "Net Money in the bank ( Worth )( spending )": 15,
    "Debt ( GBP K )": 75.0,
    "Net Position": -60.0,
    "Financial Baby Step": "2024-02-01T00:00:00",
    "Rationale": "Existential",
    "Type": "E/S",
    "Work Structure": "Deterministic - Probalistic",
    "Market": "SRE",
    "Company Lead": "Cap Gemini",
    "Ocean Type": "Red",
    "Government": 1.0,
    "BCI Direction     ( v SRE/ DEVOPS ^)": "UP/DOWN",
    "Trending Keywords And Direction": "SRE",
    "Passport Access": 185.0,
    "Security Clearance": "SC pending , nato can be invalid not used",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "SC posibility and control room access",
    "Audience": "Domestic Enterprise -Security Clearance",
    "Marketing Type": "Pull / Push",
    "Lead Source": "Referal",
    "Passport/Visa": "British  + Turkish  +Nato Security Clerance",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 10.0,
    "Materials": "Workstation",
    "COUNTRY": "UK READING",
    "location city ": "READING UK",
    "delivery": "hybrid",
    "mobility(km)": 150.0,
    "concurrency ": 1,
    "tax status": "inside ir35",
    "role": "SRE",
    "Duration month": 24,
    "type": "Employee, Business",
    "Skills Added Symbols": "Openshift / Kubernetes / Screen Writing",
    "Github Projects": 120.0,
    "CV Linkedin Projects": 72.0,
    "pound month ( net/gross )": 7000,
    "pound per hour": 43.75,
    "production income": 0,
    "Corp/Customer Generated Revenue": 114000,
    "Tax ( personal/Corporate )": "",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "Support All Family > Ece mental support",
    "Description / GAP / Marketing / Learned ": "Complex cluster management > tax payments immobilised > could not move the READING"
  },
  {
    "year": 2026,
    "Age > born 1980": "BB",
    "Net Money in the bank ( Worth )( spending )": "",
    "Debt ( GBP K )": 0.0,
    "Net Position": "",
    "Financial Baby Step": "",
    "Rationale": "Existensial",
    "Type": "B",
    "Work Structure": "Probalistic",
    "Market": "AI",
    "Company Lead": "Delivery Pilot",
    "Ocean Type": "Blue",
    "Government": "",
    "BCI Direction     ( v SRE/ DEVOPS ^)": "",
    "Trending Keywords And Direction": "AI Solution Architect",
    "Passport Access": "",
    "Security Clearance": "",
    "whyhired(Upsell) / => whatadded?(Leverage/Antifragile)": "DevAIOps CI/CD framework > Consulting,Coaching,Contribution > Cross Chasm Omantel > Build Orchestrators / Udemy and Consulting Sales on Implementation 100k and 1m product service > delivery pilot",
    "Audience": "",
    "Marketing Type": "Pull",
    "Lead Source": "CAnva to Linkedin Lead Magnets > Product WebSite",
    "Passport/Visa": "Domicile Dynamic / ILR / E2",
    "Productivity ( Speed > Reuse skills,materials(code,machines))": 20.0,
    "Materials": "workstation",
    "COUNTRY": "Production Set",
    "location city ": "onsite to remote",
    "delivery": "",
    "mobility(km)": "",
    "concurrency ": "",
    "tax status": "",
    "role": "",
    "Duration month": "",
    "type": "",
    "Skills Added Symbols": "partners sales, scheduling,Video Production, AI at all stage asistans",
    "Github Projects": 200.0,
    "CV Linkedin Projects": 80.0,
    "pound month ( net/gross )": "",
    "pound per hour": "",
    "production income": "",
    "Corp/Customer Generated Revenue": "",
    "Tax ( personal/Corporate )": "stayin",
    "increase rate to previous": "",
    "tr min wage": "",
    "uk min wage": "",
    "loose team count": "",
    "state": "",
    "Asistants - Support": "",
    "Description / GAP / Marketing / Learned ": ""
  }
];
